version: 2

jobs:
  build:
    working_directory: ~/revision
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make install-dev
      - run:
          name: Run lint
          command: make lint
      - run:
          name: Run test
          command: make test
